### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by she3o**
## Types of Changes

> What types of changes does your PR introduce? Put an x in all boxes that apply

- [ ] New addition to list
- [ ] New category to list
- [x] Fixing bug in existing item in list
- [ ] Removing item from list
- [x] Changing structure (organization) of list

## Proposed Changes

1. 1444a32: Change contributing file to CONTRIBUTING.md and fix link to it from README.md
2. 0d19bb1: Add badges to every Github repo in README.md. This was actually performed by a couple of AWK scripts that I wrote for this.
3. 0d85dc3: Revert Commit 0d19bb1 because there is a better approach. I didn't reset 0d19bb1 because it is a valid commit in its own right.
4. b17c5ff: Add GitHub wokflow to generate README.md from _README.md. Add AWK scripts as submodule.

## PR Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.

- [x] I have read the CONTRIBUTING guide
- [x] I have explained why this PR is important
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by she3o** [comment]
Actually I think it's better if we had a manual_readme.md for stuff humans write and a Makefile/Python script that takes that file and generates a README.md for GitHub. What do you think?

**Comment by MohamedElashri** [comment]
> Actually I think it's better if we had a manual_readme.md for stuff humans write and a Makefile/Python script that takes that file and generates a README.md for GitHub. What do you think?

Hi, Thanks for the PR. I will accept that. 

I think having separate one will be nice but will need to clarify that in contributing.md. Would you open an issue to track that. Or a PR if you feel ambitions?

**Comment by she3o** [comment]
Great. I am going to do the following:

1. Revert back to the commit where I fix the link.
2. Rename `README.md` to `_README.md`
3. The scripts I used are hosted in `she3o/AWKward`. I will create a branch with only those scripts.
4. Add that branch as a submodule to `MohamedElashri/awesome-zotero`
5. Add a Makefile that runs the AWK scripts on `_README.md` to generate `README.md`
6. Add note in `CONTRIBUTING.md`

Does this sound like a reasonable plan?

**Comment by MohamedElashri** [comment]
> Great. I am going to do the following:
> 
>     1. Revert back to the commit where I fix the link.
> 
>     2. Rename `README.md` to `_README.md`
> 
>     3. The scripts I used are hosted in `she3o/AWKward`. I will create a branch with only those scripts.
> 
>     4. Add that branch as a submodule to `MohamedElashri/awesome-zotero`
> 
>     5. Add a Makefile that runs the AWK scripts on `_README.md` to generate `README.md`
> 
>     6. Add note in `CONTRIBUTING.md`
> 
> 
> Does this sound like a reasonable plan?

Great, sounds like a plan!

Go for that and if you want to use the same PR, we can modify the information in the PR text.

**Comment by she3o** [comment]
I don't generate the `README.md` because it would inflate my contribution to this repo. Instead I try to implement a GitHub Action to create `README.md` after each commit changing `_README.md`. However This is the first time I use GitHub Actions so it should be vetted first.

An alternative is @MohamedElashri running `make` on the first commit following this PR.

```Makefile
# Makefile
README.md: _README.md scripts/awk/addGithubShields.awk scripts/awk/makeShieldsSquare.awk
	awk -f scripts/awk/addGithubShields.awk _README.md | awk -f scripts/awk/makeShieldsSquare.awk > README.md
```

So after we resolve this, I will push a final commit to CONTRIBUTING.md explaining the new changes.

**Comment by she3o** [comment]
It works on my machine, 

```
 $ ./script
Cloning into 'awesome-zotero'...
remote: Enumerating objects: 131, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 131 (delta 26), reused 1 (delta 0), pack-reused 76 (from 1)
Receiving objects: 100% (131/131), 53.57 KiB | 741.00 KiB/s, done.
Resolving deltas: 100% (68/68), done.
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 14 (delta 2), reused 13 (delta 1), pack-reused 0 (from 0)
Unpacking objects: 100% (14/14), 8.15 KiB | 4.07 MiB/s, done.
From https://github.com/MohamedElashri/awesome-zotero
 * [new ref]         refs/pull/23/head -> pr-23
Switched to branch 'pr-23'
Submodule 'scripts/awk' (https://github.com/she3o/AWKward) registered for path 'scripts/awk'
Cloning into '/tmp/awesome-zotero/scripts/awk'...
Submodule path 'scripts/awk': checked out '9546dc0876ae7ac402395bdcfdd9dd9f5f521ae1'

$  cd awesome-zotero && cat README.md
# Expected file
```

which means you are not running 

```
$ awk --version
GNU Awk 5.3.1, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)
```

I thought AWK would never break compatibility. Anyway, I will rewrite the scripts in Python. Hopefully it will work everywhere.

**Comment by she3o** [comment]
If @MohamedElashri checks `main.py` and it works, next commit will update GitHub Actions and add note to CONTRIBUTING.md

```
chmod a+x main.py
./main.py _README.md > README.md
```

**Comment by MohamedElashri** [comment]
> If @MohamedElashri checks `main.py` and it works, next commit will update GitHub Actions and add note to CONTRIBUTING.md
> 
> ```
> $ chmod a+x main.py
> $ ./main.py _README.md > README.md
> ```

Great, That now works. But we will need to change the Github Action to use the python script not awk. Also would you name `main.py` to something more descriptive like `generate_readme.md` ? or any similar name.

**Comment by MohamedElashri** [comment]
Great, I think this will work. The Github action would need to run over PRs so that it is tested that it will produce correct `README.md`. Do you want to add that or should I put that later? 

Something like that would be good to the `on:` part of the action

```
  pull_request:
    branches: ['**']
```

**Comment by MohamedElashri** [comment]
Great, Thanks for the effort. I have merged the PR. For future reference 

I needed to disable main branch requiring PR to commit otherwise the bot will fail to commit directly. Also I think running this on pull_request is wrong. We should have a separate action for testing new PRs that will not include the commit part (otherwise it will always fail).

**Comment by MohamedElashri** [comment]
I added #24 to so this separation in CI Github Actions.

**Pull request merged**
